ViaVerde/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomeView
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('services/', include('services.urls', namespace='services')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('page/', include('pages.urls', namespace='page')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('', HomeView.as_view(), name="index"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import BlogView
from . import views

app_name="blog"

urlpatterns=[
    path('blog/', BlogView.as_view(), name="blog"),
    path('category/<int:category_id>/', views.category,name="category"),

]

contact/urls.py
from django.urls import path
from . import views

app_name="contact"

urlpatterns=[

     path('contact/', views.contact,name="contact"),

]

core/urls.py
from django.urls import path
from core.views import Home,About

app_name="core"

urlpatterns=[

    path('', Home.as_view(), name="home"),
    path('about/', About.as_view(), name="about"),




]

pages/urls.py
from django.urls import path
from . import views

app_name="pages"

urlpatterns=[
  path('<int:page_id>/', views.page,name="page"),

]

registration/urls.py
from django.urls import path
from .views import SingUpView

urlpatterns=[
  path('signup/', SingUpView.as_view(), name="signup"),



]

services/urls.py
from django.urls import path
from services.views import ServicesView

app_name="services"

urlpatterns=[

    path('services/', ServicesView.as_view(), name="services"),

]

blog/models.py
from turtle import update
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
  name= models.CharField(max_length=100, verbose_name="Nombre")
  created=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
  updated=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")

  class Meta:
    verbose_name="categoría"
    verbose_name_plural="categorías"
    ordering= ['-created']

  def __str__(self):
    return self.name

class Post(models.Model):
  title = models.CharField(max_length=100, verbose_name="Titulo")
  content = models.TextField(verbose_name="Contenido")
  published = models.DateTimeField(verbose_name="Fecha de publicacion", default=now)
  image = models.ImageField(verbose_name="Imagen", upload_to="blog", null=True,blank=True)
  author = models.ForeignKey(User, verbose_name="Autor", on_delete=models.CASCADE)
  categories = models.ManyToManyField(Category,verbose_name="Categorias", related_name="get_posts")
  created=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
  updated=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")


  class Meta:
    verbose_name="entrada"
    verbose_name_plural="entradas"
    ordering= ['-created']

  def __str__(self):
    return self.title

contact/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.
class Page(models.Model):
  title = models.CharField(verbose_name="Titulo", max_length=100, unique=True)
  content= models.TextField(verbose_name="Contenido")
  created=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
  updated=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")


  class Meta:
    verbose_name="Pagina"
    verbose_name_plural="Paginas"
    ordering= ['title']

  def __str__(self):
    return self.title

services/models.py
from django.db import models

# Create your models here.
class Services(models.Model):
  title= models.CharField(max_length=200, verbose_name="Titulo")
  subtitle= models.CharField(max_length=200, verbose_name="Subtitulo")
  content = models.TextField(verbose_name="Contenido")
  image = models.ImageField(verbose_name="Imagen")
  created= models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
  update = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")


  class Meta:
    verbose_name = "servicio"
    verbose_name_plural = "servicios"

  def __str__(self):
    return self.title

social/models.py
from django.db import models

# Create your models here.
class Link(models.Model):
  key = models.SlugField(verbose_name="Nombre clave", max_length=100, unique=True)
  name= models.CharField(max_length=200, verbose_name="Red social")
  url = models.URLField(verbose_name="enlace", max_length=200, blank=True, null=True)
  created=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
  updated=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")


  class Meta:
    verbose_name="enlace"
    verbose_name_plural="enlaces"
    ordering= ['name']

  def __str__(self):
    return self.name

contact/forms.py
from django import forms

class ContactForm(forms.Form):
  name = forms.CharField(label="Nombre", required=True, widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}), min_length=3,max_length=15)
  email=forms.EmailField(label="Email", required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}), min_length=3,max_length=15)
  content =forms.CharField(label="Contenido", required=True, widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Mensaje'}), min_length=3,max_length=15)

ViaVerde/views.py
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):
  def get(self, request, *args, **kwargs):

      return render(request, 'home.html')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView
from django.views.generic import View
from django.template import Template, Context
from .models import Category, Post

# Create your views here.

class BlogView(View):
  def get(self, request, *args, **kwargs):
    posts = Post.objects.all()
    context={
      'posts':posts

     }
    return render(request, 'blog.html', context)

def category(request, category_id):
  category = get_object_or_404(Category, id=category_id)
  return render(request, 'category.html',{'category':category})

contact/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.urls import reverse
from .forms import  ContactForm
from django.views.generic.edit import CreateView
from django.core.mail import EmailMessage

# Create your views here.
def contact(request):
  contact_form= ContactForm()
  if contact_form.is_valid():
    name = request.POST.get('name','')
    email = request.POST.get('email','')
    content = request.POST.get('content','')

    email = EmailMessage(
      "Via Verde: Mensaje de contacto",
      "De {} <{}>\n\nEscribio_\n\n{}".format(name, email,content),
      "no-contestar@inbox.mailtrap.oi"
      ["t.canette@gmail.com"],
      reply_to=[email]
    )
    try:
       email.send()
    except:
       return redirect(reverse('contact')+"?ok")

  return render(request, 'contact.html', {'form':contact_form})

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class Home(TemplateView):
  template_name = 'home.html'

class About(TemplateView):
  template_name = 'about.html'

pages/views.py
from django.shortcuts import render, get_object_or_404
from .models import Page

# Create your views here.
def page(request, page_id):
  page = get_object_or_404(Page, id=page_id)
  return render(request, 'sample.html', {'page': page})

services/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic import View
from django.template import Template, Context
from .models import Services

# Create your views here.
class ServicesView(View):
  def get(self, request, *args, **kwargs):
    services = Services.objects.all()
    context={
      'services':services

     }
    return render(request, 'services.html', context)

social/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Blog{% endblock %}

{% block content %}

{%for post in posts%}

<div class="header">
  <h2></h2>
</div>
<section class="container">
  <div class="row">
    <div class="rightcolumn">
      <div>
        <span><p>{{post.published}}</p></span>
        <p><strong>Publicado por:</strong>  {{post.author}}.</p>
      </div>
    </div>
    <div class="leftcolumn">
      <div class="card">
        <h1>{{post.title}}</h1>
        <div class="fakeimg img-fluid"><img src="{{post.image.url}}" width="100%" height="100%" alt="..."></div>

      </div>
    </br>
      <p>{{post.content}}.</p>

      <em>
        <p>Categoría: </p>
        {% for category in post.categories.all %}
        <a class="link" href="{% url 'blog:category' category.id %}">{{category.name}}</a>{% if not forloop.last  %},{% endif %}
        {%endfor%}
      </em>

    </div>
  </div>

</section>


{%endfor%}

{% endblock %}

blog/templates/category.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Blog{% endblock %}

{% block content %}

{% for post in category.get_posts.all %}

<div class="header">
  <h2></h2>
</div>
<section class="container">
  <div class="row">
    <div class="rightcolumn">
      <div>
        <span><p>{{post.published}}</p></span>
        <p><strong>Publicado por:</strong>  {{post.author}}.</p>
      </div>
    </div>
    <div class="leftcolumn">
      <div class="card">
        <h1>{{post.title}}</h1>
        <div class="fakeimg img-fluid"><img src="{{post.image.url}}" width="100%" height="100%" alt="..."></div>

      </div>
    </br>
    <p>{{post.content}}.</p>
    <em>

      <p>Categorías: </p>
      {% for category in post.categories.all %}
      <a class="link" href="{% url 'blog:category' category.id %}">{{category.name}}</a>{% if not forloop.last  %},{% endif %}
      {%endfor%}
    </em>
    </div>
  </div>

</section>


{%endfor%}

{% endblock %}

contact/templates/contact.html
{% extends 'base.html' %}

{% load static %}


{% block content %}

<h1 class="titulo" id="contacto">Contáctanos</h1>
<div class="container2">
{% if 'ok' in request.GET %}
  <h1>Mensaje enviado</h1>
{%endif%}
  <form id="basic-form"  method="post">
      {% csrf_token %}
   <div class="row">
      <div class="col-md-4"></div>
           <div class="col-md-6">
               <h2>Ingrese sus datos</h2>
               <div class="form-group">
                   <label for="nombre">Name: </label><br>
                   {{form.name}}


                 </div>
                 <div class="form-group">
                     <label for="nombres">Email:</label><br>
                     {{form.email}}

                    </div>

                    <div class="form-group">
                      <label for="nombres">Contenido:</label><br>
                      {{form.content}}
                    </div>
                    <p class="text-warning">*Debe completar todos los campos para enviar</p>
                    <button type="submit" class="botton" id="enviar">Enviar</button>
                   </div>
             </div>
           </div>
     </form>
    </div>


{% endblock %}

core/templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container">
  <h1 class="titulo">Planes</h1>
  <div class="row">
    <div class="col-md-4">
      <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Plan 1</h5>
          <p class="card-text">Una extracción a la semana $5000</p>
          <a href="{% url 'contact:contact' %}" class="botton">Contáctanos</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card" style="width: 18rem;">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Plan 2</h5>
        <p class="card-text">Una extracción a la semana $5000</p>
        <a href="{% url 'contact:contact' %}" class="botton">Contáctanos</a>
      </div>
    </div>
  </div>
    <div class="col-md-4">
      <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Plan 3</h5>
          <p class="card-text">Una extracción a la semana $5000</p>
          <a href="{% url 'contact:contact' %}" class="botton">Contáctanos</a>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock %}

core/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Inicio{% endblock %}

{% block content %}
<style>
  /*estilos-centro*/
.aside {
  width: 100%;
  transition: width 1s;
  transition-delay: 0.5s;
  list-style: none;

  color:#063712;
 margin-top:10%;
 text-align:center;
 background-color:#ccc;
 border-radius:30px;
 font-family:'Comic Sans MS';
 font-size:30px;
}

  .aside:hover {
      width: 200px;

  }

  .jumbo {
    color: #063712!important;
    font-family: 'Comic Sans MS' !important;
    padding: 4%;

}
.titulos{
  text-align: center!important;
}
/*estilos-centro-fin*/

</style>
<!--slider-->
<p>{{hora_now}}</p>
<div class="container2 slider">
   <div class="row">
     <div class="col-md-12">

       <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
         <div class="carousel-indicators">
           <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
           <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
           <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
         </div>
         <div class="carousel-inner">
           <div class="carousel-item active">
             <img src="{% static 'img/fondo-reciclaje.jpg' %}" class="d-block  img-fluid" alt="...">

           </div>
           <div class="carousel-item">
             <img src="{% static 'img/activacion-exter.jpg' %}" class="d-block w-100 img-fluid" alt="...">

           </div>
           <div class="carousel-item">
             <img src="{% static 'img/reciclaje_vidrio_dos.jpg' %}" class="d-block w-100 img-fluid" alt="...">

           </div>

         </div>
         <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
           <span class="carousel-control-prev-icon" aria-hidden="true"></span>
           <span class="visually-hidden">Previous</span>
         </button>
         <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
           <span class="carousel-control-next-icon" aria-hidden="true"></span>
           <span class="visually-hidden">Next</span>
         </button>
       </div>
     </div>
   </div>
 </div>


 <!--slider-fin-->
 <div class="container">

  <div class="row">
    <h1 class="titulos">¿Sabes como reciclar?</h1>
    <h4 class="titulos">Conoce los pasos</h4>
      <div class="col-md-6 jumbo  ">
          <img src="{% static 'img/uno.png' %}" width="50" height="50" />
          <p>Entrega los materiales limpios</p>
          <img src="{% static 'img/dos.png' %}" width="50" height="50" />
          <p>Reduce al máximo, para utilizar menos espacio</p>
          <img src="{% static 'img/tres.png' %}" width="50" height="50" />
          <p>Separa en contenedores cada material</p>

      </div>
      <div class="col-md-6">

          <ul>
              <li class="aside">Límpia<img src="{%static 'img/ic-limpio.png'%}" width="50" height="50" /></li>
              <li class="aside">Reduce<img src="{%static 'img/ic-reduce.png'%}" width="50" height="50" /></li>
              <li class="aside">Separa<img src="{%static 'img/ic-separa.png'%}" width="50" height="50" /></li>
          </ul>
      </div>


  </div>

 </div>


{% endblock %}

pages/templates/sample.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="header">
  <h2></h2>
</div>
<section class="container">
  <div class="row">
    <div class="rightcolumn">

        <h1><strong>{{page.title}}</strong></h1>.</strong></h1>

    </div>
    <div class="rightcolumn">
      <div class="l">
        <p>{{page.content}}, </p>


      </div>
    </div>
    <div>
      {% if user.is_authenticated %}
      <p><a href="{% url 'admin:pages_page_change' page.id %}">Editar</a></p>
      {%endif%}
    </div>
  </div>

</section>



{% endblock %}

services/templates/services.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Principales Colaboradores{% endblock %}
{% block content %}
<div class="container2">
  <h1> Colaboradores</h1>
  <p>Los materiales reciclados luego de pasar por un proceso son enviados a las distintas empresas que los utilizan como materia prima.</p>

</div>
  {%for service in services %}

  <section>
    <div class="container">


      <div class="row s">

        <div class="col-md-6 col-sm-12">
          <div class="container3">
            <div class="card">
              <div class="card-title"><h3>{{service.title}}</h3></div>

                <div class="face face1">
                    <div class="content">
                        <div class="icon">
                          <img src="{{service.image.url}}" width="100%" height="250px" alt="...">
                        </div>
                    </div>
                </div>
                <div class="face face2">
                    <div class="content">
                       <p>{{service.subtitle}}</p>
                    </div>
                </div>
            </div>
          </div>
        </div>

        <div class="col-md-6 col-sm-12">
            <h3>{{service.title}}</h3>
            <p>{{service.content}}</p>

        </div>

    </div>
    </div>
  </section>

  {% endfor %}











<style>

.s{
  padding-top: 2%;
}


.container3 {
    width: 100%;
    position: relative;
    display: flex;
    justify-content: space-between;
}

.container3 .card {
    position: relative;
    border-radius: 10px;
    background-color: #424542;
}
.imagenes .card .icono{
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 80px;
  transition: 0.7s;
  color: #fff;
}

.container3 .card .icono {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: #f00;
    transition: 0.7s;
    z-index: 1;
}

.container3 .card:nth-child(1) .icono {
    background:#063712;
}

.container3 .card:nth-child(2) .icono {
    background: #063712;
}

.container3 .card:nth-child(3) .icono {
    background: #4aada9;
}


.container3 .card .icono .img{
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 80px;
    transition: 0.7s;
    color: #063712;
}

.container3 .card .face {
    width: 300px;
    height: 200px;
    transition: 0.5s;
}

.container3 .card .face.face1 {
    position: relative;
    background: #333;
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 1;
    transform: translateY(100px);
}

.container3 .card:hover .face.face1{
    background:  #063712;
    transform: translateY(0px);
}

.container3 .card .face.face1 .content {
    opacity: 1;
    transition: 0.5s;
}

.container3 .card:hover .face.face1 .content {
    opacity: 1;
}

.container3 .card .face.face1 .content imagenes{
    max-width: 100px;
}

.container3 .card .face.face2 {
    position: relative;
    background:gray;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 20px;
    box-sizing: border-box;
    box-shadow: 0 20px 50px rgba(0,0,0,0.8);
    transform: translateY(-100px);
    border-radius: 10px;
}

.container3 .card:hover .face.face2{
    transform: translateY(0);
}

.container3 .card .face.face2 .content p{
    margin: 0;
    padding: 0;
    text-align: center;
    color: black;
}

.container3 .card .face.face2 .content {
    margin: 0 0 0 0;
    padding: 0;
    font-size: 24px;
    text-align: center;
    color: #414141;
}

.container3 {
    text-decoration: none;

}
.imagenes {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 80px;
  transition: 0.7s;
  color: #fff;
}

</style>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Via verde</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/slider.css' %}">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://kit.fontawesome.com/8a7b024440.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light fixed ">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/logo.png' %}" style="width: 150px" alt="logo_via_verde">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav topBotomBordersOut ">
            <li class="nav-item active">
              <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:about' %}">Planes</a>
              </li>


            <li class="nav-item">
                <a class="nav-link" href="{% url 'services:services' %}">Colaboradores</a>
              </li>

            <li class="nav-item">

            </li>



            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
              </li>

                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Acceder</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'signup' %}">Registro</a>
                </li>
                {% else %}

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'contact:contact' %}">Contacto</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Salir</a>
                </li>
                {% endif %}

          </ul>
        </div>
      </div>
    </nav>


  {% block content %}
  {% endblock content %}
<div class="container2">

    <footer class="footer">
        <div class="footer-left col-md-4 col-sm-6">
          <p class="about">
            <span> Sobre nosotros</span> Nuestra compañia esta dedicada, al reciclaje de distintos materiales.
          </p>
          <div class="icons">
            {% if LINK_FACEBOOK %}
            <a href="{{LINK_FACEBOOK}}" target="_blank"><i class="fa fa-facebook"></i></a>
            {% endif%}
            {% if LINK_TWITER %}
            <a href="{{LINK_TWITER}}" target="_blank"><i class="fa fa-twitter"></i></a>
            {% endif%}
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-google-plus"></i></a>
            {% if LINK_INSTAGRAM %}
            <a href="{{LINK_INSTAGRAM}}" target="_blank"><i class="fa fa-instagram"></i></a>
            {% endif%}
          </div>
        </div>
        <div class="footer-center col-md-4 col-sm-6">
          <div>
            <i class="fa fa-map-marker"></i>
            <p><span> El cuzco 33</span> San Felipe, Chile</p>
          </div>
          <div>
            <i class="fa fa-phone"></i>
            <p> (+56) 9999 555 444</p>
          </div>
          <div>
            <i class="fa fa-envelope"></i>
            <p> office@company.com</p>
          </div>
        </div>
        <div class="footer-right col-md-4 col-sm-6">
          <h2><span><img src="{% static 'img/logo.png' %}" style="width: 150px" alt="Ggatunos"></span></h2>
          <p class="menu">
            <a href="#"> Home</a> |
            <a href="#gallery1"> Noticias</a> |
            <a href="#gallery2"> Galería</a> |
            <a href="#contacto"> Contacto</a> |

          </p>

        </div>
        <div class="center">
          <p>
          {% load pages_extras %}
          {% get_page_list as page_list %}
          {% for page in page_list %}
          <a class="link" href="{% url 'pages:page' page.id %}">{{page.title}}</a> .
          {% endfor %}

          </p>
        </div>
      </footer>


</div>


    <script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>Index</h2>

{% endblock content %}